name: mcp_sip_dart
description: Model Context Protocol implementation in Dart
version: 1.0.0

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  web_socket_channel: ^3.0.2
  universal_io: ^2.2.2
  yaml: ^3.1.3

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
