name: semantic_intent_framework_flutter
description: Semantic Intent Framework for Flutter
version: 1.0.5
# temporary disabled
publish_to: none
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.6.2
  flutter: ^3.27.0

# resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  semantic_intent_framework_dart:
    path: ../semantic_intent_framework_dart

# path: ^1.8.0
dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
