name: semantic_intent_framework_dart
description: A starting point for Dart libraries or applications.
version: 1.0.2
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.2

resolution: workspace

# Add regular dependencies here.
# dependencies:
# path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
